//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnoJueces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jueces
    {
        public int id { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> TOTAL_CARPETAS { get; set; }
        public Nullable<int> FORMULACIONES { get; set; }
        public Nullable<int> ORDENES_A { get; set; }
        public Nullable<int> CONTROL_DETENCION { get; set; }
        public Nullable<int> DELITO_ALTO_IMPACTO { get; set; }
        public Nullable<int> DELITO_BAJO_IMPACTO { get; set; }
        public Nullable<int> TOTAL_IMPUTADOS { get; set; }
        public Nullable<int> TOTAL_VICTIMAS { get; set; }
        public string ESTATUS { get; set; }
        public string ALIAS { get; set; }
    }
}
